#LeticiaSanto _
##  Oiii! Eu sou a Letícia Santos 👋
- 🌱 Estudante de Análise e Desenvolvimento de Sistemas
- 😃 Pronomes: ela/dela



<div align="center">
  <a href="https://beacons.ai/LeSantos1015">
  <img height="180em" src="https://github-readme-stats.vercel.app/api?username=LeSantos1015&show_icons=true&theme=dracula&include_all_commits=true&count_private=true"/>
  <img height="180em" src="https://github-readme-stats.vercel.app/api/top-langs/?username=LeSantos1015&layout=compact&langs_count=7&theme=dracula"/>
</div>


  <div style="display: inline_block"><br>
  <img align="center" alt="Rafa-Js" height="30" width="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-plain .svg">
  <img align="center" alt="Rafa-Ts" height="30" width="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-plain .svg">
  <img align="center" alt="Rafa-React" height="30" width="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original .svg">
  <img align="center" alt="Rafa-HTML" height="30" width="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original .svg">
  <img align="center" alt="Rafa-CSS" height="30" width="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original .svg">
  <img align="center" alt="Rafa-Python" height="30" width="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original .svg">
  <img align="center" alt="Rafa-Csharp" height="30" width="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/csharp/csharp-original .svg">
  <img align="right" alt="" height="150" style="border-radius:50px;" src="https://media.discordaap.net/attachments/639956127056134178/890373478988013628/Publicacoes_Instagram_1_1.png?width=676&height=676">
</div>


##

<div>       
  <a href="https://www.instagram.com/leticiasanto_s/" target="_blank"><img src="https://img.shields.io/badge/-Instagram-%23E4405F?style=for -the-badge&logo=instagram&logoColor=white" target="_blank">
  </a>
  <a href="https://discord.gg/wagxzStdcR" target="_blank"><img src="https://img.shields.io/badge/Discord-7289DA?style=for-the-badge&logo= discord&logoColor=white" target="_blank">
  </a>
  <a href = "mailto:contatoleticia.espro@outlook.com"><img src="https://img.shields.io/badge/-Gmail-%23333?style=for-the-badge&logo=gmail&logoColor=white " target="_blank">
  </a>
  <a href="https://www.linkedin.com/in/leticia-pereira-dos-santos-b0a7b3212" target="_blank"><img src="https://img.shields.io/badge/ -LinkedIn-%230077B5?style=for-the-badge&logo=linkedin&logoColor=white" target="_blank">
  </a>
<a href="https://codepen.io/leticiasanto-s" target="_blank"><img src="https://img.shields.io/badge/Codepen-000000?style=for-the- badge&logo=codepen&logoColor=white" target="_blank">
  </a>

  ![ Animação de cobra ](https://github.com/rafaballerini/rafaballerini/blob/output/github-contribution-grid-snake.svg)

</div>
